#!/usr/bin/perl
# $Header: /work/in/../cm431fp1rcs/reload-mn,v 1.5 2010/01/20 20:18:32 rcompos Exp $
#
# IBM USDA Forest Service CM423 TMR
# Description : Re-install existing Tivoli Linux RHEL gateway 
#               managed node products and patches.
#      Author : Ron Compos, Consulting Science LLC
#        Date : 2011-05-19
#
# *** For Red Hat Enterprise Linux (RHEL) managed nodes only ***
#

use strict;
use Getopt::Std;
use Cwd;

unshift( @INC, "/usr/local/Tivoli/etc/script/lib" );
require "tool.pl";
require "tooltiv.pl";

select( ( select( STDERR ), $| = 1 )[0] );
select( ( select( STDOUT ), $| = 1 )[0] );

my %opt;
getopts( 'a:dfhl', \%opt );
if( $opt{ h } ) { usage() }
$main::dbug  = $opt{ d } ? 1 : 0;
my $dbug     = $main::dbug;
my $force    = $opt{ f } ? 1 : 0;
my $list     = $opt{ l } ? "-l" : "";
my $action   = $list     ? "LIST" : "INSTALL";
my $reload   = $opt{ a } ? "-a $opt{ a }" : "";
$main::xs    = 0; print $main::xs if $dbug;
if( ! $ARGV[0] ) { usage( "No arguments supplied" ) }
my $host = $ARGV[0];
my $_x_         = $opt{ l } ? 4      : 0;

my $ult            = "/usr/local/Tivoli";
my $ults           = "$ult/src";
my $ulte           = "$ult/etc";
my $ultes          = "$ulte/script";
my $ultec          = "$ulte/cfg";
my $gw_cfg1        = "$ultec/inst/gw431-rhel-1of2.cfg";
my $gw_cfg2        = "$ultec/inst/gw431-rhel-2of2.cfg";

my $reg            = get_region();
my $mn             = $host;
my $host_inv;


my @mn_info = get_mn();
my( $mn_label, $mn_oid, $obj_no ) = ( $mn_info[0], $mn_info[1], $mn_info[2] );
unless( $obj_no =~ /\d+\.1\.0/ ) { usage ("Must be run from TMR server" ) }
if( "$mn_label" eq "$mn" ) { usage( "Cannot specify TMR server managed node as target" ) }

title( "DEBUG", 40, 5 ) if $dbug;

unless( -f $gw_cfg1 ) { print "ERROR: File not found: $gw_cfg1\n"; exit 1; }
unless( -f $gw_cfg2 ) { print "ERROR: File not found: $gw_cfg2\n"; exit 1; }

vhx( "wlookup -r ManagedNode $mn", 3, 1  );

title( "$action Tivoli products and patches: $mn", 10, 0 );
confirm( $force ) unless $list;
print "\n";

my $start_time = time;
print "    Start_Time : ", scalar localtime, "\n\n" unless $list;

# Install first set of products/patches
vhx( "$ultes/loadtiv -f $list $reload -c $gw_cfg1 -s $ults $mn", 0, 1 ); 

# Force install of MDist Console
vhx( "winstall -y -c $ults/fwk431inst2of2/JAVA/ -i MD2G431F \@IgnoreSubsumed@=1 $mn", $_x_, 0 );

# Install second set of products/patches
vhx( "$ultes/loadtiv -f $list $reload -c $gw_cfg2 -s $ults $mn", 0, 1 ); 

unless( $list ) {
    my( $hour, $min, $sec ) = runtime( $start_time );
    print  "\n";
    print  "  Managed Node : $mn\n";
    print  "        Region : $reg\n";
    print  "      End_Time : ", scalar localtime, "\n";
    printf "      Run_Time : %02d h %02d m %02d s\n",$hour, $min, $sec;
    print "\n$0 complete.\n\n";

    print "The managed node needs to be restarted\n";
}

############################
#        end corpus        #
############################


sub usage {
    print "$_\n" for( @_ );
    print STDERR <<"USAGE";

Usage: $0 [-fhl] [-a <args>] <managed_node>

Desc:  Re-load/install Tivoli products/patches on the managed 
       node.  Specify any gateway managed node. The default 
       config file will be used (gw.cfg).  Config file contains 
       a list of product/patch definitions, one per line.

       May be re-run if necessary.
       Must be run from the TMR server.
       The TMR server cannot be specified as a target.

       -a  args for overwrite ( "BIN=! LIB=! LCF=! MAN=! CAT=!" )
           All dirs will be overwritten if only "!" is supplied
       -f  force, no prompt
       -h  help
       -l  list config file without performing install

USAGE
exit 0;
}   # end sub usage

